import 'package:flutter/material.dart';

// Colors
Color primaryColor = const Color(0xff79133f);
Color secondaryColor = const Color(0xffa11950);

// Lists
var departments = [
  "Please select a department*",
  "Architecture",
  "Aviation and Space Sciences",
  "Business",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "City and Regional Planning",
  "Civil Aviation",
  "Civil Engineering",
  "Communication",
  "Computer Engineering",
  "Cybersecurity Engineering",
  "Dentistry",
  "Design",
  "Economics",
  "Education",
  "Electrical and Electronics Engineering",
  "Energy",
  "Engineering",
  "Engineering and Natural Sciences",
  "Entrepreneurship",
  "Fine Arts",
  "Foreign Languages",
  "Geological Engineering",
  "Health Sciences",
  "Humanities and Social Sciences",
  "Informatics",
  "Interior Architecture",
  "International Relations",
  "Law",
  "Landscape Architecture",
  "Logistics",
  "Maritime Studies",
  "Mathematics",
  "Mechanical Engineering",
  "Medicine",
  "Metallurgical and Materials Engineering",
  "Mining Engineering",
  "Molecular Biology and Genetics",
  "Music",
  "Natural and Applied Sciences",
  "Petroleum and Natural Gas Engineering",
  "Pharmacy",
  "Physics",
  "Political Sciences",
  "Psychology",
  "Science",
  "Social Sciences",
  "Sociology",
  "Software Engineering",
  "Sports Sciences",
  "Tourism",
  "Urban Design and Landscape Architecture",
  "Aerospace Engineering",
  "Environmental Science",
  "Robotics Engineering",
  "Nursing",
  "Agricultural Sciences",
  "Biomedical Engineering",
  "Data Science",
  "Biotechnology",
  "Environmental Engineering"
];

var genders = [
  "Please select a gender*",
  "male",
  "famale",
  "unselected",
];

var grades = [
  "Please select a grade*",
  "1",
  "2",
  "3",
  "4",
  "5",
];

var degrees = [
  "Please select a degree*",
  "Dr.",
  "Prof.",
  "Prof. Dr.",
  "Asst. Prof. Dr.",
  "Assoc. Prof.",
  "Asst. Prof.",
  "Lecturer",
  "Research Assistant",
  "Teaching Assistant",
  "Instructor",
];
